# Generated by Django 5.2.11 on 2026-02-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
